### ISSUE TITLE
dialog: non-pausing dialog causes flickering in the time/pause button

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#102]
eg. the golem in the gear room at the start of soa.

**Comment by bradallred** [comment]
GUIWORLD has code to focus the portrait and option windows after opening the button. I'm sure this issue would be resolved by either doing the same with the clock window (if the clock should be visible) or by hiding the clock window.

**Comment by lynxlynxlynx** [comment]
the clock is on the option window.

**Comment by bradallred** [comment]
I don’t believe that is how it is in the original. For example you can minimize the options window and the clock will remain.

**Comment by lynxlynxlynx** [comment]
Or the window is replaced or the messagewindow changed. Better to look at where the controls are — and if they were generated in the original too.

**Comment by bradallred** [comment]
yeah, I wont take much convincing that the original did something silly.

I'll have to debug to say anything useful, but simply having overlapping windows shouldn't be the problem. Are you talking about the golem from the beginning cutscene or the "Jailkeep Golem" in the rom north of start? I talked to that one and the clock is still ticking so I think that qualifies as "non-pausing" dialog. I didn't see any flickering issues with that.

**Comment by lynxlynxlynx** [comment]
Jailkeep, it would take too much time to go to the other one. Keeps flickering.

I also see too fast clock animation (it should take about a second for a full period), but that's not related to dialogs.

**Comment by bradallred** [comment]
I meant the one that interrupts Irenicus, but I see that doesn't use "dialog".

I can't see any flickering... Can we get a windows build I might try in wine?

the 30 FPS cap is probably broken or disabled; I'm pretty sure that governs the animation speed. I always test will sanitizers+lldb so I'm lucky to get 30 fps unless I run fullscreen :p

**Comment by bradallred** [comment]
I doubt that has any affect, but perhaps you can play with the window position in `OpenDialogButton` so we can at least confirm or rule out if it has anything to do with the window overlapping the clock. Might need to do the same with the message window.

you can set the `Draggable` flag on the all windows in the ctor and drag them around with the mouse by dragging on their background if that is easier.

**Comment by lynxlynxlynx** [comment]
This is fixed; I'm betting on the fps cap fix.
