### ISSUE TITLE
crash on init

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#106]
something with the recent hotkey changes:
```
Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x00007ffff45f00c6 in GemRB_Button_SetHotKey (self=0x7fffeaf14140, args=0x7fffeaf11050)
    at /home/kajak/dev/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:3050
3050            btn->SetHotKey(hotkey[0], mods, global);
(gdb) p hotkey
$1 = (unsigned char *) 0x7fff00000000 <error: Cannot access memory at address 0x7fff00000000>
```

I just wanted to drive-by test something else; not much time to look into things right now.

**Comment by bradallred** [comment]
I can't seem to reproduce and address sanitizer makes no complaints. when you say "init" I assume you literally mean you can't even make it to the start screen.

is this a specific game?

**Comment by bradallred** [comment]
I think with 518adcd you should at least get a runtime error instead of a hard crash. The bt makes it seem like the "hotkey" was a 0 length string

**Comment by lynxlynxlynx** [comment]
Fine now. And yes, it was bg2 before windows.
