### ISSUE TITLE
Paper Doll rendering incorrectly under SDL2

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#113]
possibly the unknown "shadow" stuff I had no idea about

on the plus side they look kinda cool!

![image](https://user-images.githubusercontent.com/1126744/38166960-3809e868-34ea-11e8-9373-97e1a8416d50.png)

**Comment by lynxlynxlynx** [comment]
Looks like a classic palette issue (default clown colors).

**Comment by bradallred** [comment]
It may just be coincidence, but while trying to get a handle on the loading crash it was reported that we have some undefined behavior in `Palette::SetupPaperdollColours`

**Comment by bradallred** [comment]
Unfortunately this didn't fix the SDL 2 issue with PST chargen/guirec portrait. I'll open a new issue for that.
