### ISSUE TITLE
inventory: unusuable items blink the whole overlay

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#117]
... instead of just the border. So it's an ugly white-red animation.

I'm not sure why you added the white on-hover border in the first place.

**Comment by bradallred** [comment]
On Inventory items? probably an accidental find and replace. its an optional parameter on `SetBorder` that is false by default. Its there for the portrait buttons as per the original (BG 2 at least). I don't believe it is used for anything else.

**Comment by bradallred** [comment]
can you add the details please? (game, driver, screenshot or video)

this is what i see in BG2:
![bg2-inv-pulse](https://user-images.githubusercontent.com/1126744/38253507-0f7f8994-3714-11e8-8834-5ccbe8ef498c.gif)


we can certainly turn them off here (I don't think the original has borders at all), but they shouldn't be making anything "unusable". So the question is are the portrait buttons also "unusable"?

**Comment by lynxlynxlynx** [comment]
Unusable items are items one can't use. For Keldorn, I'd expect the wand of magic missile to fit that category, but it's easier if you switch to Imoen or Edwin. They get a red overlay.

I do see the overlays in sdl1, bg2, subviews. This is what the bug was reported on.

**Comment by bradallred** [comment]
Ah, I totally misunderstood you. Makes sense now. Thanks.

**Comment by bradallred** [comment]
still need to remove the pulse flag from these in GUIScripts, but looks fine now
