### ISSUE TITLE
More Efficient Text Rendering

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#120]
One known bottleneck in the SDL 2 renderer is the way we print colorized text using a palette, rather than a color modulation on a desaturated palette. Specifically, I'm talking about the `Palette`s from `GemMarkupParser::GetSharedPalette`. We could ditch this entire cache and just use a single palette + color. Just would need to add a new method to `Font` to take a color and add the `BLIT_TINTED` flag.

If you uncap the FPS then open the large message text window and fill it up with text you will notice a substantial difference vs if the window is closed. I know some of that is due to the printing rather than the rendering, but since changing colors requires a cache flush (destroying and recreating the texture) and we change colors back and forth multiple times it makes sense that this has a big impact on performance.

**Comment by lynxlynxlynx** [comment]
This was done already and is tracked on the main tracker.
