### ISSUE TITLE
SDL2: items drawn over fog

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#122]
![image](https://user-images.githubusercontent.com/1126744/38468778-fa480658-3b07-11e8-8a1a-a245442a5937.png)

Seems like the best thing to do might be to add a check for the fog before trying to draw anything, but I'm not sure how to do that. This actually would likely be a performance boon to all drivers since we wouldn't be drawing things that are covered.

**Comment by lynxlynxlynx** [comment]
I'm not sure it would help. Wouldn't they get drawn over shroud of war too?
An optimisation would be possible via the explored bitmap, but it's coarse, so that wouldn't fix everything.

**Comment by bradallred** [comment]
This seems to only be happening with dead actors (and items), the living behave properly for both fog types.

Of course, a partially "obscured" actor would still fully visible I assume (maybe not if their `SpriteCover` accounts for full fog), so you are right, its not really a fix, but it would be an improvement and also a potential performance win to cull them.

a full fix would be to draw the fog on the top layer, but still might look into culling

**Comment by lynxlynxlynx** [comment]
What makes bodies and ground piles different? As it sounds like something that could fixed on load, not on draw.

**Comment by bradallred** [comment]
I'm afraid that is beyond my current knowledge.

**Comment by bradallred** [comment]
If we just implement the suggested fix for #111 this should presumably disappear.
