### ISSUE TITLE
Convert `Point` from short -> int

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#124]
There are several issues stemming from the use of the `short` type in `Point`.

1. incompatible with `Region` and `Size` (they use `int`)
2. cannot cast to `SDL_Point` which is a performance bottleneck in some places (issue #123)
3. IWD2 (possibly EE) uses 4 bytes for them
4. PST Journal must be truncated due to overflow

there is also a lot of code that could be cleaned up where we want to assign a point/size to a `Region`, but cannot because the use of short prevents defining `Region` in terms of a `Point` + `Size`

**Comment by lynxlynxlynx** [comment]
now a duplicate
