### ISSUE TITLE
msgwin causes optwin and/or portraitwin drawing issue

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#125]
we show two stripes, like there was a modal window, even if there is none. Example from the original:
https://img.youtube.com/vi/Jnmn1ZumUrI/0.jpg

... I noticed now that it's a different issue — the two windows are not getting drawn. I didn't start with them hidden.

**Comment by bradallred** [comment]
I'm not exactly sure what you are saying or how to reproduce it. is it a specific game? any script error?

**Comment by lynxlynxlynx** [comment]
I just started a dialog in bg2, nothing special.

**Comment by bradallred** [comment]
You arent helping me to understand.

<img width="912" alt="screen shot 2018-04-19 at 3 22 36 pm" src="https://user-images.githubusercontent.com/1126744/39019397-6269b79a-43e6-11e8-98f4-01dcc99ba303.png">

to me this looks like the original. I don't see an issue here. Does it happen at a certain resolution? SDL1? SDL2? can you screenshot the problem?

**Comment by lynxlynxlynx** [comment]
sdl1, the side windows aren't displayed, just their modal overlay. 800x600

**Comment by bradallred** [comment]
ah, yes, now I can reproduce. It seems to be a regression in the SDL1 driver. Thanks.

![image](https://user-images.githubusercontent.com/1126744/39019935-3f219922-43e8-11e8-8d6d-1f6cec945713.png)

**Comment by bradallred** [comment]
I havent made sense of it yet, but 36ebc94 is somehow responsible. Of course that commit also broke the build for SDL1 so e27c57c must be applied on top to see it.

**Comment by bradallred** [comment]
scratch that; didnt clean before build. 1e1bcf9 is the culprit.

**Comment by bradallred** [comment]
Obviously I've been running under SDL2 for the last long while. I stumbled across various other issues/crashes while fixing this! Wont be surprised if there are more to be found :(
