### ISSUE TITLE
soa intro shows broken fades

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#127]
The screen just goes instantly black instead of transitioning. Three or four occurrences.

https://youtu.be/E9XnOkA31Hg?t=8m12s

**Comment by bradallred** [comment]
SDL1 I assume? since 2 works fine here.

**Comment by lynxlynxlynx** [comment]
always, unless stated otherwise.

**Comment by lynxlynxlynx** [comment]
if you have a save in the pocket plane, the area loading upon loading the game shows the same problem.

**Comment by bradallred** [comment]
looks like this worked until 0680c80

I already tried every blend combination with 8bit sprites, but maybe we can use 24 or 32 bit. its slower of course, so not ideal. I'll look into other solutions with the blend pipeline too.

**Comment by bradallred** [comment]
looks like there was a similar issue with SDL2 and a flag was added to cope with how things need to be blended.
