### ISSUE TITLE
rightclicking on msgwin TA shows textedit cursor

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#130]
which also enables you to start typing and things go sour fast.

**Comment by bradallred** [comment]
yeah, several issues were listed in the TODOs for the text editing. currently we have no flag for toggling editability. Its the thing I'm currently focused on.

right now every single `TextArea` allows editing. It will be fixed soon.

**Comment by bradallred** [comment]
a whole slew of commits for text editing presumably fixed this

Have you noticed any remaining TAs that allow editing that shouldn't? or perhaps some that should but don't?

**Comment by lynxlynxlynx** [comment]
we can open new bugs if so.
