### ISSUE TITLE
tooltip text: eating up newlines / bad width calc

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#132]
![image](https://user-images.githubusercontent.com/121515/39086710-5ad12750-4596-11e8-94f0-7d3448435521.png)

For kobold commandos it tries to draw three lines and only manages "Kobold Comma".

**Comment by bradallred** [comment]
looks like the primary issue is that there is no newline between creature and status. Then again that doesn't explain the Kobolds.

if you could list the creature codes in the issue that would be very helpful.

**Comment by lynxlynxlynx** [comment]
there isn't a creature I don't see this with, so you can just try whatever is handy in your saves.

**Comment by bradallred** [comment]
looks like at least part of the issue is in `GameControl::TooltipText()` for actors in party it does look like it adds a newline, but i dont see anything doing that for other creatures.
