### ISSUE TITLE
no easy way to reset the action bar

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#134]
if you look at the innate spell list for example, the only way to get back to the main bar is by switching characters twice or opening and closing one of the main windows. Even opening containers and dialogue doesn't cut it.

in master a gamecontrol righttclick is enough, while I don't remember if escape worked.

**Comment by bradallred** [comment]
nice find, i'll look at what the originals do too.

**Comment by bradallred** [comment]
both should work now

original any click on the game viewport would work but I don't think we want to be executing the `UpdateActionbar()` function on every click.
