### ISSUE TITLE
scroll bams not displaying in shops

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#137]
they either appear as almost not there or otherwise malformed. Tried only in bg2.

**Comment by bradallred** [comment]
you mean scrollbars or tooltips? I didn't see any issues other than window frames that shoudn't be there. Screenshot maybe?

**Comment by lynxlynxlynx** [comment]
scrolls as in items. I see now that there's a pattern to the corruption — part of the background area mos is displayed (changes when scrolling).

Restoration:
![screenshot_20180626_075708](https://user-images.githubusercontent.com/121515/41891901-8698869a-7916-11e8-8234-dd11533c6a84.png)

It's not really just some scrolls or the last item position. A different shop shows the problem with other random items.

**Comment by bradallred** [comment]
I can't seem to reproduce with either SDL 1 or 2. I removed the alpha channel from those windows, so theoretically it is fixed. Not sure if we have any "top windows" that require an alpha, but none come to mind.
