### ISSUE TITLE
Need to address continuous buttons

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#17]
705379b (and some previous commits) removed the "repeat click" code from the event manager. The idea is to use repeat action capabilities of `Control` and set the repeat delay individually on the appropriate buttons instead of relying on a global state with limited options.

**Comment by bradallred** [comment]
This functionality is back, but most of the GUIScripts that require this behavior need to still be updated to call `Control.SetActionInterval(interval)`

**Comment by lynxlynxlynx** [comment]
This was done, you can close it.

**Comment by bradallred** [comment]
Thanks!
