### ISSUE TITLE
moving to main?

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#26]
I see you're syncing with the branch on the main repo — I guess we can continue there directly and slowly kill of the remaining reports here? Less work for me this way, since I can commit stuff directly.

**Comment by bradallred** [comment]
that was by accident, but it is fine by me.

I didn't want to inundate people with noise about this, but if nobody is going to complain then lets do it.

**Comment by lynxlynxlynx** [comment]
it's fine, there's not many of us and activity breeds activity.

**Comment by lynxlynxlynx** [comment]
Started working there, closing. I'll open new bugs there too.
