### ISSUE TITLE
mapwindow map drawing issues

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#30]
split off:
> I was researching why the map window is not working and found the problem. During the refactoring of CreateControl calls last year, inheriting of the reused control's size (frame/region) was removed. All the map creation is explicitly called with an empty region, so the control creation fails. The control's window is not available in the binding though, so that will have to change.

> IIRC the map control has a bunch more wrong with it than that... I've been ignoring that. I think I have a stash from last year that got it halfway working again.

**Comment by bradallred** [comment]
assuming everything works (doubtful 😛), the only thing remaining is to define and execute custom actions for `MapControl`. Theoretically the old callbacks should still work at that point.

**Comment by bradallred** [comment]
I'm sure we will need another issue for the world map BTW

**Comment by lynxlynxlynx** [comment]
The cursor update needs to happen on mouseup too — the palm cursor from moving the viewport persists until you move the mouse otherwise.

The names of the map notes never show due to bad coordinates.

**Comment by bradallred** [comment]
the coordinates are fine, I just checked them. The only issue I can see is the label isn't linked up yet.

**Comment by bradallred** [comment]
label is hooked up now. anything else?

**Comment by lynxlynxlynx** [comment]
They were sometimes negative when I looked, but yeah, works fine now.
Didn't test fog exploration nor farsight.

**Comment by bradallred** [comment]
closing this. its best to open a new issue when we are able to test farsight and fog.
