### ISSUE TITLE
mouse hover* events not implemented

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#31]
Similar to drag, nothing is firing them now.

**Comment by bradallred** [comment]
hmmm, they both used to work

**Comment by bradallred** [comment]
well, what do you mean by "hover". AFIK you are talking about these event handlers:
`View::OnMouseEnter`
`View::OnMouseLeave`
`View::OnMouseOver`

and for drag:
`View::OnMouseDrag`

**Comment by lynxlynxlynx** [comment]
the names are from the action names: Hover, HoverBegin, HoverEnd. That and the fact that it's near impossible to get tooltips is what I'm going off.

**Comment by bradallred** [comment]
I'm not sure anything is binding to those yet. the tooltips for buttons used to work (if they no longer do), but I dont think those were implemented using a callback.

**Comment by lynxlynxlynx** [comment]
So then, are they useful to have at all?

**Comment by bradallred** [comment]
they will be. I don't remember the specifics anymore, but some of the `UpdateXXXWindow` functionality can be replaced with callbacks for these events so we end up just updating the changed parts as they change.

something for much further down the road of course.

**Comment by lynxlynxlynx** [comment]
Only Hover is left unbound, so perhaps this can be closed.

**Comment by lynxlynxlynx** [comment]
Hover would be useful if we needed to do something each tick while hovering (as opposed to begin/end). Can't think of anything that would need that right now, so just closing.
