### ISSUE TITLE
ACTION_IS_SCREEN is unused

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#32]
maybe you have it in some stash, so just noting here.

**Comment by bradallred** [comment]
pretty sure this is for future use with touch screen events

**Comment by lynxlynxlynx** [comment]
It'll have to change then too, since Control::MouseLeave doesn't exist — I guess it was renamed to Control::HoverEnd.

**Comment by lynxlynxlynx** [comment]
Fixed it, but left it in. 🤷🏾
