### ISSUE TITLE
wrong rightclick binding?

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#33]
I looked why the inventory is so sad. Rightclicking doesn't work for me to get item descriptions. Through some random luck, I noticed middle-click does. So I suspect we have the wrong key for IE_GUI_BUTTON_ON_RIGHT_PRESS in the EventMap. Can you confirm with your mouse?

**Comment by bradallred** [comment]
I'll look into this when i get home.

the event map in Python is using mouse button "2"
`GEM_MB_MENU` is defined as 4

indeed it looks like all the right mouse button Python events are wrong

in fact, the event map should probably be using the constants themselves to ensure proper mapping
example:
`IE_GUI_BUTTON_ON_RIGHT_PRESS: lambda control, handler: control.SetAction(handler, IE_ACT_MOUSE_PRESS, 2, 0, 1)`
ought to be:
`IE_GUI_BUTTON_ON_RIGHT_PRESS: lambda control, handler: control.SetAction(handler, IE_ACT_MOUSE_PRESS, IE_GUI_BUTTON_ON_RIGHT_PRESS, 0, 1)`

**Comment by lynxlynxlynx** [comment]
fixed, but I used the proper constants. This one just happened to have the same value and would look even odder for the other events.
