### ISSUE TITLE
resting shows closing windows is not enough

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#34]
movies require the full screen, blacked.

This will take a while to retest, as it's not possible to trigger most cutscenes or stores now. Just testing regular resting: ok; with windows: top window doesn't stay on top, the messagewindow obscures it.

**Comment by bradallred** [comment]
I don't think resting needs to close windows at all. does resting need to do more than play the video?

**Comment by lynxlynxlynx** [comment]
they need a black frame, otherwise the gui is showing. Try resting, it will be obvious.

**Comment by bradallred** [comment]
yes, sounds like this FIXME needs to be addressed: Interface.cpp@2851

**Comment by lynxlynxlynx** [comment]
shouldn't that black rect there be enough?

**Comment by bradallred** [comment]
not in the case of the resting video. the  FIXME is there because this only works for the main videos since the gamewindow is the only one in existence which is full screen. once we are in game that is not true so filling the window buffer with black (no matter how large the rectangle is) will only fill the top window.

the fix is easy enough. I think we need a way to hide everything but the gamecreen anyway for cutscenes (I think there is supposed to be a way to toggle them via hotkey too).

**Comment by lynxlynxlynx** [comment]
yes, both sidebars have separate buttons and hotkeys. I don't remember about the messagewindow, but I'd say no, since there's no button.

**Comment by bradallred** [comment]
for hiding individual windows we can do `window.SetVisible(bool)`.

This seems to be what the cutscene setting is currently doing now actually. wondering if it should just call `WindowManager::HideAllWindows` and `WindowManager::ShowAllWindows` instead. AFIK cutscenes shouln't have any windows visible.

Right now its probably a non-issue, but imagine a mod that adds some kind of new window. that window wouldn't be hidden by cutscene mode currently.

**Comment by lynxlynxlynx** [comment]
cutscenes need to close everything, yes, both for seeing everything and then dialog to work. One part of resting doesn't trigger them atm for the very same reason, hiding there would be better than closing, since we need the return value or somesuch.

I'm pretty sure some textscreens happen during cutscenes, via an action (chapters) or regular master area "movement".

**Comment by bradallred** [comment]
yes, some cutscenes do need dialog. If we don't do so already, we just need to have the function that starts dialog call `window.setvisible(true)` on the dialog window.

I think hiding everything is the way to go. Parts that require a window should explicitly set visibility on the required window.

**Comment by bradallred** [comment]
this issue should be fixed by the last series of commits.

also, if we were hiding windows for resting, we can undo that; its just unnecessary extra code.

**Comment by lynxlynxlynx** [comment]
This will take a while to test, as it's not possible to trigger most cutscenes or stores now. Just testing regular resting: ok; with windows: top window doesn't stay on top, the messagewindow obscures it.

**Comment by bradallred** [comment]
something else must be focusing the MW... I'm not going to worry about that right now. something for later.

**Comment by lynxlynxlynx** [comment]
maybe happens automatically as the resting feedback is printed.

**Comment by bradallred** [comment]
that sounds likely

**Comment by bradallred** [comment]
looks like resting closes the window now. is that expected? it seems to be how the original behaves.

**Comment by lynxlynxlynx** [comment]
depends on how soon it happens. We do it on purpose so dream scripts can run.

**Comment by bradallred** [comment]
Do you know how we can fully test this?

**Comment by lynxlynxlynx** [comment]
Ok, this is now fine. One more thing to solve, but that will be an improvement over master, so can wait.
