### ISSUE TITLE
pst inventory is probably broken

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#35]
a8b784c16214 removed too much code in InventoryCommon.

Long-term, ItemHash should probably go or everyone should use it.

also #46

**Comment by lynxlynxlynx** [comment]
Is there a good reason for the new btn parameter? It's never passed, so the brokage is wider.

**Comment by bradallred** [comment]
the reason for the param is likely so we can bind that as a button event callback somewhere

**Comment by bradallred** [comment]
I don't have a good save to test this. Wanna take a quick look?

I'm sure something is broken, but a list would be nice. Never played PST before so I have no idea about a comprehensive test.

**Comment by lynxlynxlynx** [comment]
One obvious thing to check is scrolling between items in the item description window. I think the hash is also used in the float window inventory displays.

**Comment by bradallred** [comment]
im afraid i dont quite understand any of that :(

Can you upload a save for testing?

**Comment by lynxlynxlynx** [comment]
No save is necessary, just inspect an item. You'll see the window allows for iterating over the whole inventory, unlike in other games where you have to close and reopen it.
