### ISSUE TITLE
cg not closing its windows

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#36]
Some stages are closed via python, but at the end a few remain. This was broken in ab3d936d, where also DelAllWindows got removed from Interface::StartGameControl and so the documented behaviour of GemRB.EnterGame was lost.

Any particular reason, as it's quite handy?

**Comment by bradallred** [comment]
reason for what exactly? `DelAllWindows` was removed before that; when the window manager took over the windows.

seems like the handler for `QF_ENTERGAME` (`QuitGame` and maybe `LoadGame` too) should just ask the window manager to close all the windows.

**Comment by lynxlynxlynx** [comment]
maybe it's from the merge, but locally it's all in the same commit here. The handler did that before (via delall...), but the line just got removed, not replaced.
