### ISSUE TITLE
remove/redo lastactor remnants

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#38]
b5030f8 and more specifically the portrait dragging redesign (f31bad01) removed a bunch of lastActor setters. However, there's still plenty of code for that around.
lastActorID
lastActor
SetLastActor
GetLastActor
GemRB_GameControlSetLastActor

It just can't work anymore (ID is never set). Besides cruft, it breaks several users and is partly responsible for #6 .

**Comment by bradallred** [comment]
I had a peek at master, and the `SetLastActor` stuff removed in b5030f8 is actually dead code. The only time it is actually ran is the portrait mouse over.

It is being set here in `UpdateCursor` (for some reason) so it is working fine except in the case of the portraits. `lastActor` is apparently just the actor the mouse is over, so its not actually blocking anything like I thought.

**Comment by lynxlynxlynx** [comment]
it's still used for a bunch of cheats and arrow drawing (offscreen marker I think), see gemrb/core/GUI/GameControl.cpp:523 on master.

**Comment by bradallred** [comment]
right, but AFICT this is already being set correctly aside from the portrait hover which I believe is all that remains broken.

**Comment by bradallred** [comment]
Do we know of anything else remaining for this?

**Comment by lynxlynxlynx** [comment]
If the above works, not to my knowledge, but I haven't checked the code to see where all it is used.

**Comment by bradallred** [comment]
hmmm I think i haven't yet checked the arrow markers. everything else seems ok to me.

**Comment by bradallred** [comment]
Everything seems to function

a cleaner final solution for the offscreen markers will be addressed with issue #69
