### ISSUE TITLE
portraitwindow portraits are dudds

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#39]
Looking at selection brought me to #38, which made it obvious the portraits aren't interactive any more. The selection change handler successfully updates their borders, but that's it. No clicks work for selection, inventory opening or dragging.

**Comment by bradallred** [comment]
probably something fairly simple. probably should be looking at the button "value" rather than its "id" in `PortraitDragOp` and `Button::CompleteDragOperation` i forget the details.

**Comment by bradallred** [comment]
if thats not it, a cursory glance suggests that we can simply swap the frames of the buttons (after SwapPCs) :)

**Comment by lynxlynxlynx** [comment]
that's just dragging — like I said, no mouse interaction works.

**Comment by bradallred** [comment]
yes, but nobody has yet looked into what you mean by that yet :)

are you saying that `Window::DispatchMouseMotion` never creates a drag event? lots of possibilities on how it "doesn't work".

**Comment by lynxlynxlynx** [comment]
I haven't looked at dragging at all, since that's so rarely used. I saw that clicking doesn't work and from there it was obvious to try rightclicking and dragging. Then I wrote the report and continued the exploration I was in the middle of. The window basically behaves like it had a painted background, not controls.

**Comment by bradallred** [comment]
ok, i'll investigate further.

**Comment by bradallred** [comment]
dragging works, but now there is a label over the button so it is getting dragged...
pretty sure that label has always been there so i'm not quite sure how this was working before (Im certain it was, it was the test case when this was developed)

**Comment by lynxlynxlynx** [comment]
Ah. In master, all labels are like that, so you can default to it.

**Comment by lynxlynxlynx** [comment]
Only right-clicking remains, but that is another victim of overzealous code removal on the py side.

**Comment by bradallred** [comment]
I prefer to label it as underzealous cleanup ;)

**Comment by lynxlynxlynx** [comment]
I'll have time later today to look at it; the initial thing I found is unrelated.

**Comment by lynxlynxlynx** [comment]
ok, it was the same rightclick binding bug (#33). That's just the first hurdle though, as the passed button has an insanely big ID. Checking what that's about ...

Looks like it's the default python object id, not what the function wants to get, which is the party id. Trivial to mend back.

**Comment by lynxlynxlynx** [comment]
since it's from 961ef2038, this likely affects item dragging to others. Crashy, so no quick test possible.
