### ISSUE TITLE
huge scrollbar value range

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#40]
Don't know if it's related to the last changes in that area, but the load/save window can scroll almost indefinitely (and there's a one-off error, most likely on the py side now).

**Comment by bradallred** [comment]
yeah, the Python side is still missing a hook for `Control::SetValueRange`. thats problem 1; there may be others for these independent scrollbars. The scrollbars on windows/textareas should work great now (not that I have thoroughly tested them)

**Comment by bradallred** [comment]
this looks fixed. I didn't scrutinize it very well so let me know if there is something else wrong there.
