### ISSUE TITLE
textarea scrollbars not updating with content

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#41]
Seems like it could be several issues in one, but just load a game with a bunch of chars and let them complain of boredom or something, to fill the message window. Pausing or other new content doesn't scroll the text area and the scrollbar itself doesn't work. Had to pause/unpause several times to get it to display the later stuff (seemed like old content needed to be pushed off the history buffer).

**Comment by bradallred** [comment]
this specific issue should be fixed now, but there are others we should open tickets for. I'm sure something about dialog must be broken.

**Comment by lynxlynxlynx** [comment]
well the scrollbar works again, but not the autoscrolling. I'm reopening this since all the info is here.

**Comment by bradallred** [comment]
are you sure you are on the tip? or do you mean the animation? (issue #73)

I have no problem with new text scrolling the TA. Is it only an issue with the "bored" talk? I'm selecting actors and moving them around to produce text.

Edit: I do notice the scrollbar appearance doesn't update, but the scrolling is done, so there is that.

**Comment by lynxlynxlynx** [comment]
I don't see any animation, but that's hardly noticeable. And exactly, what I mean is that the trough position is not updated, the title of this bug.

**Comment by lynxlynxlynx** [comment]
works now.
