### ISSUE TITLE
areas of flux / wip / roadmap

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#42]
Do you still have any uncommitted, unfinished work? What parts of our systems shouldn't be touched or complained about until then? ;)

Do you have a general plan of attack, dependency graphs etc.? Github
- [ ] has
  - [ ] these
- [ ] nice
- [ ] lists we could use
Also milestones, but that's overkill imo.

**Comment by bradallred** [comment]
here you go: https://github.com/bradallred/gemrb/wiki/Roadmap-for-Merge-(and-beyond)

I have send you a collaborator invite so you can add/edit issues/docs as you see fit.

**Comment by lynxlynxlynx** [comment]
ok, thanks. I'll shut up about tas and scrolling for now and continue testing.
