### ISSUE TITLE
tooltips over gamecontrol not working

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#43]
like for getting actor names. Seems focusWin is null then so WindowManager::DrawTooltip does nothing. Maybe needs special casing.

didn't look at it from the overhead text angle yet, which is also not working.

**Comment by bradallred** [comment]
no, we shouldn't need special casing to determine the hoverWindow (I assume that is what you meant by focusWin), it should never be null (unless there are no windows). Something must be wrong somewhere (`WindowManager::DispatchEvent` or `WindowManager::NextEventWindow` is my guess)

I'll see if this window manager stash i have is relevant.

**Comment by lynxlynxlynx** [comment]
hoverWin, yes (ups). When you're over the gamecontrol, there are no windows to be hovering over, so it makes sense for it to be null (just going off the name).

**Comment by bradallred** [comment]
thats not the intent :) gamecontrol is in fact part of a window like everything else; its just not part of the windows list (because it always exists and can't be closed).

you can see that `WindowManager::NextEventWindow` will return that window if no other matches are found.

**Comment by lynxlynxlynx** [comment]
a guess would be that isScreen is false, since the keypress comes after the mouse events, so eventually hoverWin can't get set.

**Comment by lynxlynxlynx** [comment]
Works, at least initially. There's a problem with key repeats, as the tooltip soon starts to restart growing indefinitely.

**Comment by bradallred** [comment]
tooltips were implemented before repeat key presses so its likely a simple check for the event repeat count missing.

**Comment by lynxlynxlynx** [comment]
seems to be fixed, closing.
