### ISSUE TITLE
Start screen labels

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#45]
somehow these were broken and don't display text anymore. They still exist and are not obscured just the text is missing.

problem being my quick look though master branch I can't see how this text is actually being set...

**Comment by lynxlynxlynx** [comment]
if it's not manually set, then it is already there in the chu.
Which labels/text are you talking about?

**Comment by bradallred** [comment]
the GemRB ones (version etc), so not in the CHU

it is manually set, but the string variable it is using is empty; i don't know where it comes from

**Comment by lynxlynxlynx** [comment]
Maybe you removed it then — I think GEMRB_VERSION is the default thing to print if nothing was specified. Something like that is definitely the case in master.

**Comment by bradallred** [comment]
right, i see that, but still the string is empty in Python. it is set to -1 in GUIDefines.py, but that is how master is too. I searched the history for GEMRB_VERSION but nothing relevant came up.

I'm assuming something on the C++ side is setting that, but i came up empty in my search.

something for later I suppose

**Comment by lynxlynxlynx** [comment]
yea, -1 was special. I got the constants wrong, it's VERSION_GEMRB that gets added to GEMRB_STRING. Examples of where you removed this: d9bb104f and 9539ce32

There's no need to reintroduce the tooltip one though.

**Comment by bradallred** [comment]
ah, thank you!

I'll just properly set GEMRB_VERSION from `GUIScript::Init`
