### ISSUE TITLE
bag actionbar button starts to animate on hover

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#47]
Happens sometimes in the inventory too, but most reliably with the bag icon just before the quickslots in the actionbar. Just hover over them and they'll start blending to white and back to some brown.

Maybe related, maybe not, but in the inventory, slots get an animated white border when you hover over them. The speed is similar, the thing just doesn't cover the whole slot here.

**Comment by bradallred** [comment]
looks like the pulseborders I added are what is causing the "fade". the button borders have a `filled` value of true for some reason.

Don't know right now if its just wrong GUIScript parameters, or a bug somewhere.

**Comment by lynxlynxlynx** [comment]
There's still a white pulsating pixel in the top left corner. And the no-image actionbar buttons sometimes grow darker on hover. It's easiest to test with Sarevok here, when he has nothing in the quickslots.

**Comment by bradallred** [comment]
I believe the remaining issues are due to issue #63

**Comment by bradallred** [comment]
I was never really able to see this, but is it fixed now?

**Comment by lynxlynxlynx** [comment]
Yes. The extraneus white borders in the inventory are still there, but that can be handled in a different bug.
