### ISSUE TITLE
hotkeys with modkeys mistreated

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#48]
if you ctrl-j to jump around, it will also open the journal. Similarly ctrl-m&maps for debug dumps and so on.

**Comment by bradallred** [comment]
The option win buttons use the `RegisterHotKeyCallback` function, which should take the mod into account (if its not bugged), so i wonder if there are 2 events happening (one is maybe a repeat?).

also, could be that a key handler is erroneously returning false.

**Comment by lynxlynxlynx** [comment]
It's actually ResolveKey in GameControl::OnKeyPress that doesn't care. I made it skip naively for now, as I doubt anyone would want to rebind the mod keys.

**Comment by bradallred** [comment]
yeah, that works for me
