### ISSUE TITLE
you can close the actionwindow and msgwindow

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#49]
click+esc and no obvious way to get them back. They need their default hotkey revoked.

**Comment by bradallred** [comment]
its not a hot key (esc closes windows if nothing else grabs it)

this is actually the same problem as issue #14. we can probably recycle the `View::IgnoreEvents` flag on windows to simply ignore the events that aren't accepted by any subviews.

**Comment by lynxlynxlynx** [comment]
The commit isn't enough for this though, one can still close the windows the same way.

**Comment by bradallred** [comment]
AFICT everything but the message window ignores esc. Either I missed a SetFlag call, or something is using `OP_SET` where it shouldn't.

**Comment by lynxlynxlynx** [comment]
it's like before, only the options window is immune. Don't see any explicit resets either.

**Comment by lynxlynxlynx** [comment]
Yep.
