### ISSUE TITLE
broken selection via mouse rect.

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#50]
just so it's not forgotten: 5a04992d87 is to blame.

**Comment by bradallred** [comment]
I dont understand how that would break that. surely `GameControl::ChangeMap` ought to disable event handling and also reset the mouse state. You sure its not something else?

**Comment by lynxlynxlynx** [comment]
Yeah, established through bisect. You can revert it and see for yourself. Like I said in the comment, my guess is that now nothing is turning off SF_DISABLEMOUSE... But that doesn't really seem to be the case - the code looks ok and the cursor is still visible and enabled.

**Comment by bradallred** [comment]
ok, so something else somewhere might be setting `SF_CUTSCENE`, `SF_DISABLEMOUSE` and must have been relying on this to clear it... thats the only thing i can think of if the cursor isn't greyed.

the question is, should `GameControl::ChangeMap` do anything if we are in a cutscene? if it is allowed then I suppose changing map ought to clear that.

to me, it doesn't seem like changing map during a cutscene is valid behavior, but I may be wrong (do any cutscenes span multiple areas?)

**Comment by lynxlynxlynx** [comment]
Why would the cursor be grayed without SF_DISABLEMOUSE being set?

Cutscenes regularly change maps and the function is of course needed. ChangeMap is probably called while starting/loading a game too.

**Comment by bradallred** [comment]
IIRC if the `disabled` flag on a view is set you will get a greyed cursor too. In fact it may be the only thing that does it anymore.

**Comment by lynxlynxlynx** [comment]
ChangeMap is usually (if not always) over before you could see that.

**Comment by bradallred** [comment]
ok, I dont know if it will resolve the issue, but if this is called via cutscene and it was previously clearing that flag, then we should call `SetCutSceneMode(false)` at the beginning (or end since thats where it was before)

**Comment by lynxlynxlynx** [comment]
No, this is a dead end. In master it's not playing with any of this.

**Comment by bradallred** [comment]
now it makes even less sense :)

I now have to suspect `ClearMouseState()` somehow getting things stuck

**Comment by lynxlynxlynx** [comment]
it does, yes. Commenting that out is enough to get the rect back. :)

**Comment by bradallred** [comment]
still, that shouldn't have that result... `ClearMouseState()` should at worst reset things such that another click and drag ought to work.

seems to indicate some other problem somewhere. Probably one thing we should do is have GC disabled at construction time and only become enabled once a map is loaded.

**Comment by bradallred** [comment]
problem is simply that `GameControl::ChangeMap` doesn't always change the map :)

this is apparently called from the game loop every iteration too :(
