### ISSUE TITLE
bg2: fix guicg13 color window alignment/loading

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#51]
loading the window is not enough, the portrait part needs to be reloaded too (different window), otherwise it'll look wrong even if the misalignment is fixed. No idea when this got broken, the history is pretty harmless. EDIT: oh, but didn't check CharGenCommon changes.

expected:
https://i.ytimg.com/vi/jQCoYNoZaaA/hqdefault.jpg

**Comment by bradallred** [comment]
for reference:
![image](https://user-images.githubusercontent.com/1126744/30626882-2d7c8eb6-9d8a-11e7-9d4e-6e1b78a90335.png)

**Comment by lynxlynxlynx** [comment]
confirmed fixed.
