### ISSUE TITLE
Do something better for 0c8e922

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#53]

**Comment by lynxlynxlynx** [comment]
Come on, this is overengineered. All this complexity and invasive changes for something so trivial, while not event preserving the previous functionality? It's better to revert everything and just comment out the original if(0)s ...

**Comment by bradallred** [comment]
wouldn't have had to change so much if we could use C++11 😛 

the biggest change here is adding adding constructors and consolidating structs. Those changes are good regardless of where or what the debug message is. I can't see why you would complain about those.

the second biggest change was something else unrelated to logging either. rearanging things to avoid an extra loop etc. Again, don't know why this is a complaint.

so no, lets not revert everything. If these messages are really that important to you we can revert _that specifically_ if we want.

There were only a handful of messages that differ from `(%2d): Mod: %d, Type: %d`; I was of the opinion who cares until we actually need something different. Was there some other "functionality" that is missing?

**Comment by lynxlynxlynx** [comment]
I'm not complaining about the rest, but of course it doesn't belong to this branch.

You get a handful of different formats even only looking at iwd or pst. RE knowledge is hard to come by, so we shouldn't discard it just because you don't want to disable warnings for three files you never touch. :P
