### ISSUE TITLE
28af1312be effectively broke game saving

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#54]
the preview is crucial. It also makes no sense to store a full screenshot, it would just bloat the savegame.

... looks like WindowManager::GetScreenshot can now do part of it.

**Comment by bradallred** [comment]
> store a full screenshot

what do you mean? we want a screenshot of the `gamewin`, correct?

if we need to, its trivial to add either a `Region` param, or an override for `WindowManager::GetScreenshot` to get a portion of screen.

**Comment by lynxlynxlynx** [comment]
I was referring to your commit msg, which said you'd prefer saving the original screenshot, not roughly the size we need.

**Comment by bradallred** [comment]
I see. `Video::SpriteScaleDown` is still there for that since apparently we do care :) we just need to wire everything back up.

**Comment by lynxlynxlynx** [comment]
It's now back, but I wasn't able to get the other windows to hide, so the preview is wrong. But at least testing is much easier now.

**Comment by bradallred** [comment]
I think anything else wrong here is separate from the original issue.

the screenshots should look as they did before now.
