### ISSUE TITLE
magewindow doesn't refresh properly

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#55]
I was fixing something else, but then got dragged down this rabbit hole. And now gave up.

The mage window needs to use the same openwindow call for its selection-changed callback or it doesn't update properly when switching between mages and sorcerers. Different windows are involved, so it makes little sense to try to hack it from the update method.

However, it just doesn't work. OpenTopWindow closes itself, but even manually calling Close doesn't help. It's also easy to get the event to fire too often. Anything I tried mostly made it worse, usually somehow breaking selection on the portrait window.

**Comment by bradallred** [comment]
so `UpdateMageWindow` is insufficient for a selection-changed handler? seems like code from `OpenMageWindow` needs to move there. I'm sure i will have to dig deeper than that to actually understand the problem tho.

**Comment by lynxlynxlynx** [comment]
it makes no difference (besides being uglier), I also tried reloading the window from there. Almost all the code is the same, but the sorcerer version uses a different window, so on a change, we have to start from scratch.

**Comment by bradallred** [comment]
I think I have a fix for this. I just need to fix a few remaining regressions elsewhere before pushing my next set.

**Comment by bradallred** [comment]
will test when i get a save or find time to make a new char (if that is even possible currently)
