### ISSUE TITLE
assert in GemRB::Window::DispatchMouseMotion

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#56]
reproduce by furiously clicking in any (start) window. It can take a few seconds this way, but it's quite reliable. Seems to happen around chu frame borders, so try at 800x600 for best results.

Assertion `me.buttonStates' failed.
```
235                     assert(me.buttonStates);
(gdb) p me
$3 = (const GemRB::MouseEvent &) @0x7fffffffd7b0: {<GemRB::ScreenEvent> = {<GemRB::EventBase> = {
      repeats = 0}, x = 536, y = 539, deltaX = 2, deltaY = 5}, buttonStates = 0, button = 0 '\000'}
```
Looks like a part of the drag code, but with no apparent users of buttonStates later on.

**Comment by bradallred** [comment]
this assert probably doesnt _need_ to exist (as you noted we dont actually use the states here). the idea here is that if we have a drag then some button ought to be down.

I'm not sure why this is happening tho. the `trackingView` variable ought to get set to `NULL` when the mouse is released. It's almost like the events arrive out of order.

**Comment by lynxlynxlynx** [comment]
I checked and managed to crash it while the button was still pressed. But yeah, it could be from the previous pair/attempt.
Didn't manage to reproduce with portrait dragging.

**Comment by bradallred** [comment]
too early to say for sure, but we should examine the possibility of the `EventManager::mouseButtonFlags` variable getting out of sync with SDL.

**Comment by lynxlynxlynx** [comment]
It's also not universally true that a button must be down during drag — inventory item dragging.

**Comment by bradallred** [comment]
"Inventory dragging" isn't the same. `Window` is dealing with true mouse dragging (button is down followed by a movement) not a conceptual drag.

I have this mostly fixed. Looks like there is still an issue when distributing events between 2 windows. Example: mouse down inside one window then drag and release in another. the origin window will continue to think the mouse is down.

the solution is to add an implementation of `Window::OnMouseLeave` and probably move some of the `trackingView` code from `Window::DispatchMouseMotion` there

**Comment by bradallred** [comment]
this is hopefully unrelated, but is seems that the selection rect on `GameControl` no longer gets drawn.

I checked out prior to my changes and its still broken, so not sure what happened with it

**Comment by lynxlynxlynx** [comment]
suspect #50.

**Comment by bradallred** [comment]
indeed. must have forgotten about that (been gone for a while if you hadn't noticed ha ha)

can we close this then?

**Comment by lynxlynxlynx** [comment]
Sure. Please clear out your stashes before working on something new, so it'll be easier to work together.
