### ISSUE TITLE
alternative to SetKeyPressEvent?

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#58]
fc62088bf removed SetKeyPressEvent. IIRC it was initially added to switch between pcs in non-walk environments and in this branch this is handled by core.

We have SetHotKey, but it only works on buttons. One window in cg had a cheat in the original that was triggered via a hotkey. I could create a hidden button just to get it working, but that's ugly. Ideas?

**Comment by bradallred** [comment]
If it makes sense and we have a need for it, we can move `SetHotKey` from button up the hierarchy to `Control`.

you can also register they key directly with the event manager if that makes more sense.

I'm not exactly sure what action you are talking about or if there is any control at all that has responsibility for it.

**Comment by lynxlynxlynx** [comment]
Yeah, I guess it's best to bind it to the window. It was the cheat to max out the stats when rolling str/dex/...

**Comment by lynxlynxlynx** [comment]
I thought that may be best and to bind it to the window. But then you have to assign an event in the first place, so the hotkey can trigger something and for some reason _GemRB.Control_SetAction doesn't cut it, never finding the control. I think it's too much code change and effort for such a small thing, so I'll just create an invisible button.

It was the cheat to max out the stats when rolling str/dex/...

**Comment by bradallred** [comment]
that sounds like the best and cleanest solution available actually.

**Comment by lynxlynxlynx** [comment]
done, closing.

**Comment by bradallred** [comment]
after thinking about it. hot keys would have been the wrong way to go with this anyway.

the action callbacks we use for mouse events can be used for key events as well. There is even a [TODO for this](https://github.com/gemrb/gemrb/blob/subviews/gemrb/core/GUI/Control.h#L165)

again, we would have to migrate the "action" functionality up the hierarchy from `Control` to `View`, but it would work.
