### ISSUE TITLE
Game Cursors don't work

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#6]
The various `GameControl` cursors don't work. Likely anything that has special cursors is broken.

This ticket should be updated with the specific cursors so we can check them after reimplementing this.

**Comment by bradallred** [comment]
dont know if the cursors are all there now, but for sure the disabled status of the cursors remains broken. see 3c7993d.

**Comment by lynxlynxlynx** [comment]
Not sure exactly what you mean, but I did notice we erroneously show a disabled one when hovering over disabled controls. I don't remember every seeing the pointy hand cursor disabled. But it's almost unique in that regard — also the "no passage" one comes to mind.

**Comment by bradallred** [comment]
nah, the disabled cursor over a disabled control was something i added on purpose; partially for debugging and I thought it was cool :) its easy to "fix", just change the implementation for `View::IsDisabledCursor()` to return false.

**Comment by bradallred** [comment]
reopen this if i missed any, but I got everything i know of

**Comment by lynxlynxlynx** [comment]
Infopoint info cursors aren't there (the ?). 
For containers I'm not sure, perhaps it just looks odd due to the tile overlay missing.

The fact that the resulting action don't work are covered by #38 and similar. It's probably also the reason for the wrong positioning of the actor when he tries to interact.

**Comment by bradallred** [comment]
info point cursors seem to work for me (both the '?' and the circular arrows)

I'm presuming some other work has fixed them.

Tested in the throne room in the Prolog Dungeon of BG2
