### ISSUE TITLE
another label redrawing issue: ability screen

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#60]
guicg4 with str, dex and co. If you click on their names, the labels vanish and may later reappear. Could be the same issue as #59 , but this is a bit more contained if not faster to reach.

**Comment by bradallred** [comment]
being "contained" or "faster" likely simply means that there is greater overlap.

**Comment by lynxlynxlynx** [comment]
No, both are immediately reproducible. It just maybe faster to click and enter through cg than loading a game and going to the inventory. And there's less elements and code for potential interference.

**Comment by bradallred** [comment]
Oh, I understand now.

**Comment by lynxlynxlynx** [comment]
Nevermind, my fault. I broke something with the removal.

**Comment by lynxlynxlynx** [comment]
Bah, was testing on master ... it's still a problem. But it indeed looks like a duplicate, since a label and button overlap already from the chu. The label is useless, so I've removed it now, but here we could actually remove the controls at runtime if neeeded.

**Comment by lynxlynxlynx** [comment]
Out of curiosity I tried deleting the labels, but we don't support that any more — DeleteControl is only an alias for RemoveView. However, even moving them to 0,0 didn't change anything.

**Comment by bradallred** [comment]
`RemoveView` is the same thing, `DeleteControl` calls it and passes `True` for the delete param.

**Comment by lynxlynxlynx** [comment]
Yeah, but it errors out saying the view is invalid.

**Comment by bradallred** [comment]
sounds like a bug assuming you usage is right: `window.DeleteControl(subview)` and assuming `subview` is actually a View and not `None` or something.

**Comment by lynxlynxlynx** [comment]
well no, there is no view to pass, just the control id. That's how DeleteControl worked.

**Comment by bradallred** [comment]
so do `window.DeleteControl(window.GetControl(id))`

**Comment by lynxlynxlynx** [comment]
Ah, so the interface changed. I'll rather fix that, since there are still many users.

**Comment by lynxlynxlynx** [comment]
Heh, did that and reused the buttons for the text and the problem is gone. But of course another one popped up — likely the same underlying state problem. The buttons start as locked and work as locked, but furious clicking can change that. Something for another time.
