### ISSUE TITLE
formation rotation doesn't work

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#62]
perhaps related to #38, definitely visually to #6.

**Comment by bradallred** [comment]
likely broken (or more so) when `OnMouseOver` and `OnMouseDrag` became distinct.

**Comment by lynxlynxlynx** [comment]
did a quick check and GameControl::OnMouseDrag gets called nicely, but rightclicking never registers the button, so nothing happens. Which makes sense, since it gets called only through mouse motion events.

View::OnMouseDrag never gets called since Window has its own implementation ... which doesn't care about formations at all. So it looks like it needs to special-case the gamewindow case and call gamecontrol's handler there.

**Comment by bradallred** [comment]
not related to #38 unless that has something to do with modifier keys or mouse buttons

**Comment by lynxlynxlynx** [comment]
it mostly works now. The only remaining problem is that on mouse up, a new position for the whole formation is made (a new axis if you will), cancelling most of your previous work.
