### ISSUE TITLE
`IsOpaque()` implementations are too lazy when dealing with images

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#63]
We ought to be checking if the sprite has an alpha. There is no existing way to do this ATM, but it shouldn't be difficult to add.

Furthermore, at least `Button` has a variety of images and we aren't checking most of those at this time. We would need to check the image for the current button state at a minimum.

That brings me to a technically separate issue (that will probably get its own ticket eventually). Why do we have 3 different methods for assigning a picture to a `Button`?

we have:

1. a `Picture` ivar
2. a `PictureList` ivar
3. a `buttonImages` ivar

do we ever use these things in combination? (if so, when?)

seems to me it would be simpler and less confusing if we had a single picture list and a flag to determine if they are drawn stacked, or as state images. (I don't even think we need the single `Picture` at all)

in addition to that confusion I don't understand the point of the `IE_GUI_BUTTON_NO_IMAGE` flag. If we don't want an image don't assign one right? I'm sure it must not be that simple, but id like to at least document any reasons for these seemingly unnecessary complexities.

**Comment by lynxlynxlynx** [comment]
IE_GUI_BUTTON_NO_IMAGE is handy for toggling images off, so we don't need to hardcode so many resrefs into the guiscripts for when we want to display them again. It's not a bit from the CHU. I'm sure many users could be converted to just emptying the bam field, but it wouldn't be ideal for all.

As for why we have three choices, dig into history. Also, do all support paletted images or animations?

**Comment by bradallred** [comment]
when this is resolved, it might make sense to revert ccdfeac and 77b065d to (presumably) fix both issue #84 and issue #47. Eventually, it would be nice to simplify the button code regarding all these states and display oddities, but for now fixing this should suffice.
