### ISSUE TITLE
pl_uppercase redeclaration

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#64]
More of a question than anything else, but I don't understand why we need to redeclare pl_uppercase in String.cpp, since it's already done in the header. Removing it causes linker errors elsewhere though.

**Comment by bradallred** [comment]
the header declaration has `extern` so it is explicitly saying that it will be resolved at link time. Pretty sure we should just nix the `extern` tho i have no idea why t is there in the first place.

**Comment by lynxlynxlynx** [comment]
We init the arrays in Interface from a table. Could be moved to gamedata or a proper interface added.

**Comment by lynxlynxlynx** [comment]
I looked into this and found no prettier solution, so closing.
