### ISSUE TITLE
loading a game from ingame leaves guiopt open

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#68]
> tho there is an issue with the options window being open when the new game is loaded. obviously closing that window from the button handler would serve, but the appropriate thing to do is the FIXME from 24f436c

**Comment by bradallred** [comment]
after thinking more on this, I'm not sure closing all the windows would actually work yet. That would be dependent on if the GUIScript state being adequately cleaned up and reinitialized. I'm not sure at all what gemrb does with this right now.

certainly something for later; for now we either ignore it or add some `Close()` calls.

**Comment by lynxlynxlynx** [comment]
The load window itself is now fixed, but this will likely resurface again, especially suspicious of cg, once it works properly.
