### ISSUE TITLE
lower part of gamewindow invisible due to messagewindow

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#69]
it's on top, of course, but this means that areas like the slums have their southern passages obscured. A new player would never figure it out.

At the bottom of the map, the viewport should be movable to display the whole area, leaving the messagewindow to float over a void. That's exactly how it worked in the original — as soon as you increased the size of the window, you could scroll further down to compensate.

**Comment by bradallred** [comment]
i imagine the same applies to left and right side.

**Comment by bradallred** [comment]
I'm wondering how EE deals with this:
![image](https://www.baldursgate.com/img/screenshots/screen02.png)

do they add padding to the bottom of the area? or do the middle windows awkwardly obscure things and you have to scroll around it?

the problem with the way the originals worked it that doesn't play nice with having resolution independence (unless black bars count) or with future support of EE windows,

**Comment by lynxlynxlynx** [comment]
I checked, in EE you can scroll half the window height below the end of the area. It is displayed as fuzzy black, basically as if there was fog of war around it.

**Comment by bradallred** [comment]
still some work to be done but this is not longer blocking playthough.

**Comment by lynxlynxlynx** [comment]
looks ugly too, so I'm sure we'll get flak for that.

**Comment by lynxlynxlynx** [comment]
You can also stand in the blackness on the border (Trademeet), so it appears to be drawn too soon / too much.

**Comment by lynxlynxlynx** [comment]
It looks like it's drawn properly, but actors do manage to wade in slightly deeper. Maybe the border makes it appear worse, but let's just ignore it.
