### ISSUE TITLE
Inventory (drag) cursors don't work

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#7]
I guess for now we would have to set/unset this from `DragItem` and `ReleaseDraggedItem`.

**Comment by bradallred** [comment]
Reopening this because it has occurred to me the ground windows are going to be broken the same way.

**Comment by bradallred** [comment]
should be global now, so they should work for all windows

**Comment by lynxlynxlynx** [comment]
The cursor is not the right scale (or image?) though — now it's the same as inventory icons instead of being bigger.

**Comment by bradallred** [comment]
do you know how to get this by chance?

**Comment by lynxlynxlynx** [comment]
My guess would be it's a different bam frame — look one up.

**Comment by bradallred** [comment]
that the right one?

**Comment by lynxlynxlynx** [comment]
Yes, it's the correct one.
