### ISSUE TITLE
"display fade" needs to be reimplemented

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#72]
the thing from `GlobalTimer::DoFadeStep`

**Comment by bradallred** [comment]
I'm not sure where to test this other than by brute force which seems to work. I suppose there are actions I could run via console also.

**Comment by lynxlynxlynx** [comment]
Just start a new bg2 game. The initial cutscene uses fade-in/-out several times.

**Comment by lynxlynxlynx** [comment]
nope, doesn't work, neither fade was displayed.
intro also shows a transparency issue with two effects — white bg instead of transparent.

**Comment by bradallred** [comment]
Thanks, turns out i didnt realize there was a Fade in so that was broken

for the record `GemRb.ExecuteString("FadeFromColor(64)")` is the console command to trigger it from anywhere (super handy command that `ExecuteString` is!)

**Comment by bradallred** [comment]
I saw the transparency thing when I switched to SDL1, but that is a separate issue. Strangely it doesnt appear to be an issue with SDL 2. However, SDL 2 has its own issue blending GameControl text across Actors. The solution with that should be to just switch the drawing layer.
