### ISSUE TITLE
non TA/Win scrollbars need min/max value set

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#74]
see 8160303 and 835fb8f

I fixed the load screen, but there are others. the chargen stuff comes to mind.

**Comment by lynxlynxlynx** [comment]
basicaly #40? Ah, caught up on mail now.

save
inventory ground
possibly all the listresources ones
guienhancements kitwindow, 
classwindow?

**Comment by lynxlynxlynx** [comment]
should be fixed now.
