### ISSUE TITLE
need to restore the text padding in TextAreas

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#75]
this was supposed to have been moved to the TextContainer class; don't know what happened to it.

**Comment by lynxlynxlynx** [comment]
is this also causing the textual overflows? It's visible already on the soa/tob choice screen.

**Comment by bradallred** [comment]
@lynxlynxlynx no, that was caused by the hacky resizing previously done in the CHUImporter and fixed in b659662

**Comment by lynxlynxlynx** [comment]
textarea content gets clipped at the bottom (start screen, msgwin). It looks like as if the bottom padding was applied without enlarging the container.

**Comment by bradallred** [comment]
I need glasses

**Comment by lynxlynxlynx** [comment]
Fine now. :+1:
