### ISSUE TITLE
scrollbar skipping/granularity issue

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#77]
It's visible in the load window, now that the range is bounded. I have 8 saves and that means 5 graticule positions (start + 3 + end). Meaning there are quite long vertical intervals between them. If I want to scroll to the bottom by clicking on the trough, it's only possible right next to the lower control.

Basically clicks don't cause a move if the difference is not big enough. I guess we just floor instead of round when clamping the value?

On the pic, clicking where the cursor is doesn't move the scrollbar.
![spectacle nn2515](https://user-images.githubusercontent.com/121515/30653851-86cb1e2c-9e2c-11e7-8543-5bcf9f9dcd2f.png)

**Comment by bradallred** [comment]
heh, I actually recall fixing this same issue on master at one point too.

**Comment by bradallred** [comment]
Is this resolved now?

**Comment by lynxlynxlynx** [comment]
no, it's worse. Now there's only 3 positions, no matter if you have 4 or 7 saves. Start, end and middle.

**Comment by bradallred** [comment]
this issue appears resolved to me. objections to closing?

**Comment by lynxlynxlynx** [comment]
yeah, it's better.
