### ISSUE TITLE
Tooltip offset from side of screen is incorrect

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#8]
Currently tooltips are always rendered in the center of the cursor buffer so around the edges of the screen they become decoupled from the mouse even if they could fit without clipping off the screen.

kind of a minor issue; its better then them getting clipped as they would if they always centered on the cursor.

**Comment by lynxlynxlynx** [comment]
Seems to work fine, saw no clipping (besides wrong vertical padding, but that's on the inside). I did check only with actors though, since that's the only tooltip currently somewhat working — you must first select them with the mouse.

**Comment by bradallred** [comment]
I think i was seeing this with the tooltips for the options window buttons. No longer sure.

**Comment by bradallred** [comment]
yes, this is still an issue. you can see it on the portrait buttons and the option buttons.

not a big deal, but something that should be addressed at some point.
