### ISSUE TITLE
remove disabled overlay

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#84]
buttons get all brownish for no good reason, more and more as the state is reapplied. Nicely visible in cg — just start it and press enter to get to the next screen and then repeat enter while observing the Done button.

**Comment by bradallred** [comment]
do you know if this is recent?

**Comment by lynxlynxlynx** [comment]
On Fri, 06 Oct 2017 17:24:30 -0700
Brad Allred <notifications@github.com> wrote:

> do you know if this is recent?
Likely not, I think we already talked about it when there were some
issues with the action bar. Maybe the button phasing in and out thing.
Your whole github account seems to have vanished though (yikes), so I
can't search the tracker. It's specific to this branch.

Could be it's not actually an overlay, but some other rendering issue
with alpha, since we don't set up an overlay there in cg specifically.

**Comment by lynxlynxlynx** [comment]
On Fri, 06 Oct 2017 17:24:30 -0700
Brad Allred <notifications@github.com> wrote:

> do you know if this is recent?
Ah, it was a deliberate change, though you didn't specify why.

Reverting 77b065da fixes the browning.

The easiest way to see the problem is to run bg2, pick tob and single
player. The lowermost two buttons will get browned.

**Comment by bradallred** [comment]
thanks for researching that. I'll have to look at what else I was doing around that time to try and recollect why I added it.
