### ISSUE TITLE
reimplement BumpViewport

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#85]
removed in 36e6a938

**Comment by bradallred** [comment]
are you sure this is required? isn't this already clamped in GameControl?

**Comment by lynxlynxlynx** [comment]
I'm not, this was just a reminder to check once dialogs work properly. It's already fine for example by scrolling through the map window.

**Comment by bradallred** [comment]
Wanna check this now that dialogs (hopefully) are fully functional? if they arent that would be good to know too :)

**Comment by lynxlynxlynx** [comment]
DestroyAllWindows crashes for me on any bg2 load, somehow revisiting the same window.

**Comment by bradallred** [comment]
16fe6ed I'm sure then. Strange I didn't crash there.

**Comment by bradallred** [comment]
fixed by 811505f?

**Comment by lynxlynxlynx** [comment]
No, it's the iteration that's bizzare:
```
Thread 1 "gemrb" hit Breakpoint 2, GemRB::WindowManager::DestroyAllWindows (this=0x696df0)                          
    at /home/kajak/dev/gemrb/gemrb/core/GUI/WindowManager.cpp:272                                                   
272             WindowList::iterator it = windows.begin();                                                          
(gdb) p windows
$4 = std::deque with 1 element = {0x989330}
(gdb) n
273             for (; it != windows.end(); ++it) {
(gdb) 
274                     Window* win = *it;
(gdb) 
275                     win->SetFlags(Window::DestroyOnClose, OP_OR); // force delete
(gdb) p win
$5 = (GemRB::Window *) 0x989330
(gdb) n
276                     win->Close();
(gdb) 
273             for (; it != windows.end(); ++it) {
(gdb) 
274                     Window* win = *it;
(gdb) 
275                     win->SetFlags(Window::DestroyOnClose, OP_OR); // force delete
(gdb) p win
$6 = (GemRB::Window *) 0x7ffff6ae3ca0 <main_arena+96>
(gdb) n

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x0000000000008000 in ?? ()
```

win->Close() already removes the window from windows, in this case emptying it. And then the loop condition apparently succeeds.

**Comment by lynxlynxlynx** [comment]
As far as the original issue: currently the viewport moves to where the dialog takes place only after the dialog is finished, so it's still hard to check. I guess dialog pause is in effect.

**Comment by bradallred** [comment]
I see that some dialogs pause. Those are the ones that are delayed. non-pausing dialogs do work fine. I suppose this is due to the fact that I implemented the animated scroll as per the originals rather than the abrupt jump to location. the timer doesnt get ran when the game is paused. I may have to switch timing mechanisms.

**Comment by bradallred** [comment]
alternatively, we can set the animation speed to 0 (instant) if `DF_FREEZE_SCRIPTS` is set. this would give the same behavior as master, but different than the originals.

**Comment by bradallred** [comment]
turns out we already had a bypass in place for the fade. I just packaged them both up into a new method that we call from either timer `Update()` or `Freeze()`.

Now that that is out of the way, what else is left?

**Comment by lynxlynxlynx** [comment]
It moves the viewport back to where the command was issued, while it should just stay where it is.

**Comment by bradallred** [comment]
That isn't the behavior for the originals (BG2 anyway). Are we purposely wanting a deviation?

**Comment by lynxlynxlynx** [comment]
It looks like just the ees have this fixed in the bg series. Annoying if you're trying to talk to a moving target.

the original reason for the function seems to be gone. :)

**Comment by bradallred** [comment]
we can certainly remove that behavior if its unwanted. Its this line in DialogHandler.cpp:
`gc->MoveViewportTo(prevViewPortLoc, false, 75); // FIXME: arbitrary guess value`.

just delete it I suppose. Guess any code related to `prevViewPortLoc` also.

**Comment by lynxlynxlynx** [comment]
nah, it could affect the presentation of cutscenes, if any depend on that behaviour.
