### ISSUE TITLE
smallest msgwin doesn't fit two lines of text

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#86]
![](http://assets2.ignimgs.com/2000/08/22/bgb2003-177398.jpg)
a few px off; seems like a max 1px padding on bottom and maybe 3px at the top.

also works fine on master for all sizes of the window, if you want a closer look.

**Comment by bradallred** [comment]
hmmm, I copied the `EDGE_PADDING` from master to use as the margins. maybe it only applies to the sides and not the top/bottom.

**Comment by bradallred** [comment]
This is also causing this problem in the journal:
![image](https://user-images.githubusercontent.com/1126744/31980819-6d09c1dc-b90c-11e7-819e-1414f3d91f2f.png)
