### ISSUE TITLE
GUIScript::SetTooltipDelay needs to be reimplemented

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#9]
Broken in 2ddcd2f

I guess just call WindowManager::SetTooltipDelay for now. This needs to be saved in the INI too... maybe just don't worry about saving it for now and refactor the setting out of Interface and into their own manager (I actually have a prototype for this).

**Comment by lynxlynxlynx** [comment]
Added. Saving has never been done by this, but it's also obviated, since it's an ini setting. We can just remove the cfg option, which I'll do later.
