### ISSUE TITLE
clipping issues when resizing msgwin

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#91]
![screenshot_20171111_184449](https://user-images.githubusercontent.com/121515/32691970-6a910c96-c710-11e7-94cf-5c25e610d04a.png)
![screenshot_20171111_184514](https://user-images.githubusercontent.com/121515/32691973-76e5205e-c710-11e7-9db2-7afed2ce2a59.png)
![screenshot_20171111_184531](https://user-images.githubusercontent.com/121515/32691975-805db5f6-c710-11e7-8d94-8e9969554db4.png)

**Comment by bradallred** [comment]
yeah, this is a known regression I commented about in f7f5d47

I pushed it up so I could fix the dialog issues (without it the select options are not drawn). Once those are fixed I will figure out the right thing to do.
