### ISSUE TITLE
Protagonist name absent in GUIREC

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#94]
possibly other areas

**Comment by lynxlynxlynx** [comment]
everywhere, since neither actor name is stored. Yikes! Try an old gemrb/original save game to see if this happens only for subviews new chars or if something got broken in creimporter or savimporter.

**Comment by lynxlynxlynx** [comment]
definitely in one of the loaders. CG works, save and load then exhibits this bug.

**Comment by bradallred** [comment]
good to know, thanks. hopefully this weekend i'll fix this and a few remaining issues preventing smooth play testing so we can move onto getting the other games up and running.

**Comment by bradallred** [comment]
likewise, loading an original save the name is present, so the issue must lie in the save process.

**Comment by bradallred** [comment]
It was actually happening on load. the GUIREC shows the "short name" but saving requires the "long name" which was not being loaded.
