### ISSUE TITLE
Save game char portraits are too large

### ISSUE THREAD

**Issue by bradallred** [bradallred/gemrb#97]
![image](https://user-images.githubusercontent.com/1126744/33801697-af07b84a-dd20-11e7-8eb8-af8d6f70ba50.png)

top is from this branch. bottom is from original i think.

**Comment by lynxlynxlynx** [comment]
Are you sure this is a new save?

**Comment by lynxlynxlynx** [comment]
Just tried saving again, still works fine here.

**Comment by bradallred** [comment]
yeah, i see this issue with a fresh save. I should check against master to see if i see it there.

**Comment by bradallred** [comment]
either fixed or not known how to reproduce. closing until its seen again in a way that is reproducible.
