### ISSUE TITLE
can't load after saving game

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#98]
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIOPT.py", line 486, in OpenLoadMsgWindow
[Python/ERROR]:     LoadMsgWindow = Window = GemRB.LoadWindow (4)
[Python/ERROR]: RuntimeError: win cannot be null.
```
... though it looks like a misdirection. We used to close guiopt on a successful save and this doesn't happen any more, just the save windows are closed.

**Comment by bradallred** [comment]
I wasn't having a problem, but I was using the quicksave. I can tell by the code in the error the fix would be to add the window pack to the `LoadWindow` call.
